### ISSUE TITLE
SVG images are not processed

### ISSUE THREAD

**Issue by aeirola** [ahmadnassri/node-metalsmith-imagemin#22]
Imagemin supports optimizing SVG files, but metalsmith-imagemin skips any file that has the file extension .svg in [`lib/index.js:9`](https://github.com/ahmadnassri/metalsmith-imagemin/blob/a8aa52fa1022aa93276410b37ce7052a34a2b813/lib/index.js#L9).

Would it be possible to add support for svg images as well?

**Comment by ahmadnassri** [comment]
done & released in `v1.2.0` :)

**Comment by aeirola** [comment]
Awesome, big thanks for the quick response!
