### ISSUE TITLE
Incompatibility with load-metalsmith-plugins

### ISSUE THREAD

**Issue by tamlyn** [ahmadnassri/node-metalsmith-imagemin#53]
[load-metalsmith-plugins](https://www.npmjs.com/package/load-metalsmith-plugins) tries to load the version which requires babel-runtime. I don't want to install babel-runtime as I'm using Node 6. I can manually require the node6 version of this plugin but that's no help because load-metalsmith-plugins has already crashed node. I think it's a bit of an ask to install babel-runtime just to use this 70 line plugin so for now I'm going to uninstall this and call imagemin directly. 

Since this is mostly used on development machines rather than production servers, I would guess that very few if any people are using node < 4. Perhaps the node4 version should be made the default in `package.json`?

**Comment by ahmadnassri** [comment]
have you tried `npm install --production metalsmith-imagemin
` ? this would ONLY install production dependencies, which DO NOT include babel.

as good practice, its probably best to only ever do `npm install --production` on your entire project (to avoid all subsequent nested dependencies of the dependent packages)

###### Update:

I just found out, that as of `npm v3.3.0` the argument is `--only=production`
