### ISSUE TITLE
find module 'babel-runtime/core-js/object/keys'

### ISSUE THREAD

**Issue by 2pha** [ahmadnassri/node-metalsmith-imagemin#59]
Adding `var imagemin = require('metalsmith-imagemin');` to my build.js and trying to run the build, I get the error `find module 'babel-runtime/core-js/object/keys'`.
Should it be set as a dependency?
running `npm install --save babel-runtime` installed it and the errors were gone

**Comment by ahmadnassri** [comment]
I just pushed out [`v4.0.0`](https://github.com/ahmadnassri/metalsmith-imagemin/releases/tag/v4.0.0) removes babel dependency and `babel-runtime` requirement.

please note only Node `>=4` are supported going forward as per [Node's own LTS](https://github.com/nodejs/LTS)

**Comment by 2pha** [comment]
Is there something else I need to do to get this working? I can see that it is looping over the correct files (images), but the image size is the same in the build folder. Sorry, I am new to metalsmith.
The most basic built which I'm trying is below, buy it doesn't reduce file size:  
```
var imagemin = require('metalsmith-imagemin');
Metalsmith(__dirname)
  .source('./src')
  .destination('./build')
  .clean(true)
  .use(imagemin())
  .build(function(err, files) {
    if (err) { throw err; }
  });
```

**Comment by ahmadnassri** [comment]
the [default configuration is here](https://github.com/ahmadnassri/metalsmith-imagemin/blob/master/lib/index.js#L29)

no compression means the thresholds per default configuration was not reached, or your images are already optimized.

see the tests for more examples

**Comment by 2pha** [comment]
I had to update my node version, now it is working very well thanks. I was on 4.4.4, now on 6.10.0.
Thanks
